### ISSUE TITLE
SelectedIndex is not respected

### ISSUE THREAD

**Issue by naweed** [XamlBrewer/Uwp.CoverFlowSample#5]
Hi,

Firstly, love this awesome control. It is amazing.

I have found an issue. I am using the coverflow control in a HubSection and binding it (using x:Bind) to an itemsource which has 5 items. I want the third item (which happens to be the middle item) to be in focus, and two on each side. Using the SelectedIndex="2" doesn't work. Any suggestion for this.

Thanks
Naweed

**Comment by XamlBrewer** [comment]
My LexDB sample shows a way to make the Coverflow bind to SelectedItem instead of SelectedIndex. 

https://github.com/XamlBrewer/UWP-Lex.DB-Sample/blob/master/XamlBrewer.Uwp.LexDbSample/MainPage.xaml.cs

It's not really MVVM but it does the trick.

**Comment by naweed** [comment]
@XamlBrewer 
I solved it as below (and in MVVM way). Basically, I wanted to make the center item in focus. This is how to do it. Just add the following at the end of "PrepareContainerForItemOverride":

```
        if(items.Count > 2)
            IndexSelected(items.Count / 2, false);
```

Or if you want to use the SelectedIndex to highlight a specific item:

```
        if(items.Count > SelectedIndex && SelectedIndex > 0)
            IndexSelected(SelectedIndex, false);
```

Attached below is the result.

![clipboard01](https://cloud.githubusercontent.com/assets/103980/18053116/9b26be96-6e06-11e6-892f-031a1702e582.jpg)
